/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 banana.glb --transform 
Files: banana.glb [86.66MB] > C:\Users\giann\OneDrive\Documenti\portfolio3D\3d-tries\public\banana-transformed.glb [2.32MB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/banana-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Banana.geometry} material={materials.Skin} />
    </group>
  )
}

useGLTF.preload('/banana-transformed.glb')
