/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 lemon.glb --transform 
Files: lemon.glb [8.72MB] > C:\Users\giann\OneDrive\Documenti\portfolio3D\3d-tries\public\lemon-transformed.glb [663.22KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lemon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lemon.geometry} material={materials.skin} />
    </group>
  )
}

useGLTF.preload('/lemon-transformed.glb')
